### ISSUE TITLE
rubygems.org out of sync with linked repo

### ISSUE THREAD

**Issue by gkorban** [adimichele/hubspot-ruby#201]
This isn't an issue with the code itself, but I'm having a hard time reconciling the code and descriptions in this repository (https://github.com/adimichele/hubspot-ruby) with what I get when I install the gem from https://rubygems.org. Rubygems is linking to this repo as the homepage, but has different contents.  

First, Rubygems is reporting the gem to be at version 0.8.1, but the latest version bump I see in the commit history is to 0.7.0.

The code looks different as well.  For example, lib/hubspot/company.rb from Rubygems:
```ruby
module Hubspot
  #
  # HubSpot Companies API
  #
  # {http://developers.hubspot.com/docs/methods/companies/companies-overview}
  #
  class Company
    CREATE_COMPANY_PATH              = "/companies/v2/companies/"
    RECENTLY_CREATED_COMPANIES_PATH  = "/companies/v2/companies/recent/created"
```

has a different contents and inheritance from this repo:

```ruby
class Hubspot::Company < Hubspot::Resource
  self.id_field = "companyId"
  self.property_name_field = "name"

  ADD_CONTACT_PATH        = '/companies/v2/companies/:id/contacts/:contact_id'
  ALL_PATH                = '/companies/v2/companies/paged'
```

**Comment by cbisnett** [comment]
We're in the middle of refactoring a bunch of things in this library that are breaking backwards compatibility. That's why we forked the `v0-stable` branch so we could patch and update the old code while working on the refactor. I also added a warning to the top of the readme:
>This is the master branch and contains unreleased and potentially breaking changes. If you are looking for the most recent stable release you want the v0-stable branch.

If you look that the `v0-stable` branch and the README.md there you will find what you're looking for.
