### ISSUE TITLE
Blog posts should be ordered by publish_date

### ISSUE THREAD

**Issue by supremebeing7** [adimichele/hubspot-ruby#34]
https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/blog.rb#L48

Since the default params specify that blog posts state should be `"PUBLISHED"`, I would expect that they be ordered by `publish_date`. However, they are ordered by `created`. I can submit a patch for this if it seems sensible.

**Comment by supremebeing7** [comment]
Looking at the Hubspot docs, the only caveat is that filtering on `publish_date` is not allowed:
```
blog.posts(order_by: '-publish_date', publish_date__gt: Time.now - 2.month)
# => Hubspot::RequestError: Response body: {"message": "You cannot filter on the field publish_date ", "errors": [], "succeeded": false}
```
I think filtering on `updated` should solve that, since the `updated` field should be updated upon publishing. If older posts were updated, they would show up in the results, but the results would still be in order or publish date.

**Comment by cbisnett** [comment]
I think this functionality has been changed since this issue was opened. According to the current documentation, *only* `publish_date` can be used in the `order_by` field, however the tests still pass even with the current value of `-created`. I also tried completely invalid options like `foo` and that worked as well, so it's possible the API just ignores any invalid options now.
