### ISSUE TITLE
Creating Deals - Readme

### ISSUE THREAD

**Issue by ACPK** [adimichele/hubspot-ruby#73]
I see that you can create a deal (def create!(portal_id, company_ids, vids, params={})), but what's the recommended call? I'd be happy to update the readme and submit a PR. :)

**Comment by cbisnett** [comment]
You can create a deal by calling `Hubspot::Deal.create!()` like this:
```ruby
Hubspot::Deal.create!(nil, [company.vid], [contact.vid], pipeline: 'default', dealstage: 'initial_contact')
```
This will create a deal linked to a Hubspot company and contact. The first option is the portal ID, which is not required. Any properties supported by deals can be specified as options.

If you would like to submit a PR for a documentation update that would be great. Otherwise, I can add it.

**Comment by cbisnett** [comment]
I updated the documentation with an example for creating deals in 5e35bb20473708049a3bf9a2f346a68d01afb06b
